# Generated by Django 3.2.9 on 2021-11-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=11, unique=True)),
                ('mbti', models.CharField(max_length=4, null=True)),
                ('gender', models.CharField(default='U', max_length=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
