# Generated by Django 3.2.9 on 2021-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211118_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
