# Generated by Django 3.2.9 on 2021-11-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.CharField(blank=True, default='', max_length=4),
            preserve_default=False,
        ),
    ]
